language: r
cache: packages
warnings_are_errors: false
repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat","httr","jsonlite","geojsonio"));devtools::install_deps("StreetMaps")'
script:
  - Rscript -e 'devtools::check("StreetMaps")'
